spring.application.name=projeto-hora-do-rango
server.port=8081

#Banco PostgreSql
spring.datasource.url=jdbc:postgresql://localhost:5432/hora_do_rango
spring.datasource.driverClassName = org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=yoZynHjt4ce!KKmdjxL7

#Swagger
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api